import prettier from "prettier";

export const {
  check,
  clearConfigCache,
  format,
  formatWithCursor,
  getFileInfo,
  getSupportInfo,
  resolveConfig,
  resolveConfigFile,
  version,
} = prettier;

export default prettier;
export type {
  AST,
  BaseSupportOption,
  BooleanArraySupportOption,
  BooleanSupportOption,
  BuiltInParser,
  BuiltInParserName,
  BuiltInParsers,
  ChoiceSupportOption,
  CursorOptions,
  CursorResult,
  CustomParser,
  Doc,
  FastPath,
  FileInfoOptions,
  FileInfoResult,
  IntArraySupportOption,
  IntSupportOption,
  LiteralUnion,
  Options,
  Parser,
  ParserOptions,
  PathArraySupportOption,
  PathSupportOption,
  Plugin,
  Printer,
  RequiredOptions,
  ResolveConfigOptions,
  SupportInfo,
  SupportLanguage,
  SupportOption,
  SupportOptionRange,
  SupportOptions,
  SupportOptionType,
} from "prettier";
